### ISSUE TITLE
Pure must combine selectors not paying attention on quotes

### ISSUE THREAD

**Issue by Ser-Gen** [Ser-Gen/postcss-data-packer#11]
```css
.a { background-image: url(/*a.png*/); }
.b { background-image: url('/*a.png*/'); }
.c { background-image: url("/*a.png*/"); }
```

```css
.a,
.b,
.c { background-image: url(/*a.png*/); }
```
